# Generated by Django 4.0.4 on 2022-05-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_alter_data_bldgtype_alter_data_bsmtqual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BldgType',
            field=models.PositiveIntegerField(choices=[(0, 'Single-family Detached'), (1, 'Two-family Conversion; originally built as one-family dwelling'), (3, 'Townhouse Inside Unit'), (2, 'Duplex'), (4, 'Townhouse End Unit')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='BsmtQual',
            field=models.PositiveIntegerField(choices=[(1, 'Fair (70-79 inches)'), (3, 'Typical (80-89 inches)'), (2, 'Good (90-99 inches)'), (0, 'Excellent (100+ inches)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='CentralAir',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Electrical',
            field=models.PositiveIntegerField(choices=[(4, 'Standard Circuit Breakers & Romex'), (3, 'Mixed'), (2, '60 AMP Fuse Box and mostly knob & tube wiring (poor)'), (1, '60 AMP Fuse Box and mostly Romex wiring (Fair)'), (0, 'Fuse Box over 60 AMP and all Romex wiring (Average)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Foundation',
            field=models.PositiveIntegerField(choices=[(3, 'Slab'), (2, 'Poured Contrete'), (5, 'Wood'), (4, 'Stone'), (1, 'Cinder Block'), (0, 'Brick & Tile')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='GarageType',
            field=models.PositiveIntegerField(choices=[(0, 'More than one type of garage'), (5, 'Detached from home'), (2, 'Basement Garage'), (1, 'Attached to home'), (3, 'Built-In (Garage part of house - typically has room above garage)'), (4, 'Car Port')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HeatingQC',
            field=models.PositiveIntegerField(choices=[(4, 'Average/Typical'), (1, 'Fair'), (0, 'Excellent'), (2, 'Good'), (3, 'Poor')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HouseStyle',
            field=models.PositiveIntegerField(choices=[(5, 'Two story'), (7, 'Split Level'), (0, 'One and one-half story: 2nd level finished'), (3, 'Two and one-half story: 2nd level finished'), (6, 'Split Foyer'), (4, 'Two and one-half story: 2nd level unfinished'), (1, 'One and one-half story: 2nd level unfinished'), (2, 'One story')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='LotShape',
            field=models.PositiveIntegerField(choices=[(3, 'Regular'), (1, 'Moderately Irregular'), (2, 'Irregular'), (0, 'Slightly irregular')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Neighborhood',
            field=models.PositiveIntegerField(choices=[(9, 'Iowa DOT and Rail Road'), (16, 'Northridge Heights'), (17, 'Old Town'), (18, 'South & West of Iowa State University'), (10, 'Meadow Village'), (5, 'College Creek'), (6, 'Crawford'), (13, 'Northpark Villa'), (0, 'Bloomington Heights'), (14, 'North Ames'), (8, 'Gilbert'), (12, 'Northwest Ames'), (7, 'Edwards'), (15, 'Northridge'), (21, 'Somerset'), (4, 'Clear Creek'), (11, 'Mitchell'), (19, 'Sawyer'), (22, 'Stone Brook'), (2, 'Briardale'), (3, 'Brookside'), (20, 'Sawyer West'), (1, 'Bluestem'), (24, 'Veenker'), (23, 'Timberland')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofMatl',
            field=models.PositiveIntegerField(choices=[(5, 'Gravel & Tar'), (6, 'Wood Shakes'), (0, 'Clay or Tile'), (3, 'Metal'), (7, 'Wood Shingles'), (2, 'Membrane'), (4, 'Roll'), (1, 'Standard (Composite) Shingle')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofStyle',
            field=models.PositiveIntegerField(choices=[(2, 'Gabrel (Barn)'), (5, 'Shed'), (1, 'Gable'), (3, 'Hip'), (0, 'Flat'), (4, 'Mansard')], null=True),
        ),
    ]
