# Generated by Django 4.0.4 on 2022-05-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_alter_data_bldgtype_alter_data_bsmtqual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BldgType',
            field=models.PositiveIntegerField(choices=[(1, 'Two-family Conversion; originally built as one-family dwelling'), (2, 'Duplex'), (4, 'Townhouse End Unit'), (3, 'Townhouse Inside Unit'), (0, 'Single-family Detached')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='BsmtQual',
            field=models.PositiveIntegerField(choices=[(3, 'Typical (80-89 inches)'), (0, 'Excellent (100+ inches)'), (2, 'Good (90-99 inches)'), (1, 'Fair (70-79 inches)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Electrical',
            field=models.PositiveIntegerField(choices=[(2, '60 AMP Fuse Box and mostly knob & tube wiring (poor)'), (1, '60 AMP Fuse Box and mostly Romex wiring (Fair)'), (0, 'Fuse Box over 60 AMP and all Romex wiring (Average)'), (4, 'Standard Circuit Breakers & Romex'), (3, 'Mixed')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Foundation',
            field=models.PositiveIntegerField(choices=[(3, 'Slab'), (5, 'Wood'), (1, 'Cinder Block'), (2, 'Poured Contrete'), (4, 'Stone'), (0, 'Brick & Tile')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='GarageType',
            field=models.PositiveIntegerField(choices=[(5, 'Detached from home'), (3, 'Built-In (Garage part of house - typically has room above garage)'), (0, 'More than one type of garage'), (1, 'Attached to home'), (2, 'Basement Garage'), (4, 'Car Port')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HeatingQC',
            field=models.PositiveIntegerField(choices=[(0, 'Excellent'), (1, 'Fair'), (2, 'Good'), (3, 'Poor'), (4, 'Average/Typical')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HouseStyle',
            field=models.PositiveIntegerField(choices=[(3, 'Two and one-half story: 2nd level finished'), (1, 'One and one-half story: 2nd level unfinished'), (2, 'One story'), (6, 'Split Foyer'), (4, 'Two and one-half story: 2nd level unfinished'), (7, 'Split Level'), (0, 'One and one-half story: 2nd level finished'), (5, 'Two story')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='LotShape',
            field=models.PositiveIntegerField(choices=[(1, 'Moderately Irregular'), (2, 'Irregular'), (3, 'Regular'), (0, 'Slightly irregular')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Neighborhood',
            field=models.PositiveIntegerField(choices=[(14, 'North Ames'), (23, 'Timberland'), (21, 'Somerset'), (5, 'College Creek'), (6, 'Crawford'), (10, 'Meadow Village'), (8, 'Gilbert'), (13, 'Northpark Villa'), (11, 'Mitchell'), (4, 'Clear Creek'), (3, 'Brookside'), (1, 'Bluestem'), (19, 'Sawyer'), (16, 'Northridge Heights'), (0, 'Bloomington Heights'), (9, 'Iowa DOT and Rail Road'), (24, 'Veenker'), (2, 'Briardale'), (20, 'Sawyer West'), (17, 'Old Town'), (12, 'Northwest Ames'), (18, 'South & West of Iowa State University'), (7, 'Edwards'), (15, 'Northridge'), (22, 'Stone Brook')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PavedDrive',
            field=models.PositiveIntegerField(choices=[(0, 'Dirt/Gravel'), (1, 'Partial Pavement'), (2, 'Paved ')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofMatl',
            field=models.PositiveIntegerField(choices=[(5, 'Gravel & Tar'), (4, 'Roll'), (7, 'Wood Shingles'), (0, 'Clay or Tile'), (3, 'Metal'), (2, 'Membrane'), (1, 'Standard (Composite) Shingle'), (6, 'Wood Shakes')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofStyle',
            field=models.PositiveIntegerField(choices=[(4, 'Mansard'), (1, 'Gable'), (5, 'Shed'), (3, 'Hip'), (2, 'Gabrel (Barn)'), (0, 'Flat')], null=True),
        ),
    ]
