# Generated by Django 4.0.4 on 2022-05-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_alter_data_bldgtype_alter_data_bsmtqual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BldgType',
            field=models.PositiveIntegerField(choices=[(2, 'Duplex'), (3, 'Townhouse Inside Unit'), (4, 'Townhouse End Unit'), (1, 'Two-family Conversion; originally built as one-family dwelling'), (0, 'Single-family Detached')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='BsmtQual',
            field=models.PositiveIntegerField(choices=[(0, 'Excellent (100+ inches)'), (3, 'Typical (80-89 inches)'), (1, 'Fair (70-79 inches)'), (2, 'Good (90-99 inches)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Electrical',
            field=models.PositiveIntegerField(choices=[(4, 'Standard Circuit Breakers & Romex'), (3, 'Mixed'), (2, '60 AMP Fuse Box and mostly knob & tube wiring (poor)'), (1, '60 AMP Fuse Box and mostly Romex wiring (Fair)'), (0, 'Fuse Box over 60 AMP and all Romex wiring (Average)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Foundation',
            field=models.PositiveIntegerField(choices=[(0, 'Brick & Tile'), (4, 'Stone'), (3, 'Slab'), (5, 'Wood'), (1, 'Cinder Block'), (2, 'Poured Contrete')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='GarageType',
            field=models.PositiveIntegerField(choices=[(3, 'Built-In (Garage part of house - typically has room above garage)'), (4, 'Car Port'), (5, 'Detached from home'), (0, 'More than one type of garage'), (2, 'Basement Garage'), (1, 'Attached to home')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HeatingQC',
            field=models.PositiveIntegerField(choices=[(1, 'Fair'), (3, 'Poor'), (4, 'Average/Typical'), (0, 'Excellent'), (2, 'Good')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HouseStyle',
            field=models.PositiveIntegerField(choices=[(5, 'Two story'), (3, 'Two and one-half story: 2nd level finished'), (7, 'Split Level'), (4, 'Two and one-half story: 2nd level unfinished'), (6, 'Split Foyer'), (1, 'One and one-half story: 2nd level unfinished'), (0, 'One and one-half story: 2nd level finished'), (2, 'One story')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='LotShape',
            field=models.PositiveIntegerField(choices=[(3, 'Regular'), (1, 'Moderately Irregular'), (0, 'Slightly irregular'), (2, 'Irregular')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Neighborhood',
            field=models.PositiveIntegerField(choices=[(10, 'Meadow Village'), (24, 'Veenker'), (14, 'North Ames'), (19, 'Sawyer'), (12, 'Northwest Ames'), (0, 'Bloomington Heights'), (17, 'Old Town'), (5, 'College Creek'), (3, 'Brookside'), (13, 'Northpark Villa'), (9, 'Iowa DOT and Rail Road'), (11, 'Mitchell'), (18, 'South & West of Iowa State University'), (1, 'Bluestem'), (4, 'Clear Creek'), (16, 'Northridge Heights'), (6, 'Crawford'), (23, 'Timberland'), (7, 'Edwards'), (22, 'Stone Brook'), (8, 'Gilbert'), (15, 'Northridge'), (20, 'Sawyer West'), (21, 'Somerset'), (2, 'Briardale')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PavedDrive',
            field=models.PositiveIntegerField(choices=[(0, 'Dirt/Gravel'), (2, 'Paved '), (1, 'Partial Pavement')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofMatl',
            field=models.PositiveIntegerField(choices=[(4, 'Roll'), (2, 'Membrane'), (3, 'Metal'), (0, 'Clay or Tile'), (5, 'Gravel & Tar'), (6, 'Wood Shakes'), (1, 'Standard (Composite) Shingle'), (7, 'Wood Shingles')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofStyle',
            field=models.PositiveIntegerField(choices=[(5, 'Shed'), (2, 'Gabrel (Barn)'), (0, 'Flat'), (4, 'Mansard'), (3, 'Hip'), (1, 'Gable')], null=True),
        ),
    ]
