# Generated by Django 4.0.4 on 2022-07-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_alter_data_bldgtype_alter_data_bsmtqual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BldgType',
            field=models.PositiveIntegerField(choices=[(3, 'Townhouse Inside Unit'), (0, 'Single-family Detached'), (4, 'Townhouse End Unit'), (2, 'Duplex'), (1, 'Two-family Conversion; originally built as one-family dwelling')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='BsmtQual',
            field=models.PositiveIntegerField(choices=[(0, 'Excellent (100+ inches)'), (1, 'Fair (70-79 inches)'), (2, 'Good (90-99 inches)'), (3, 'Typical (80-89 inches)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Electrical',
            field=models.PositiveIntegerField(choices=[(3, 'Mixed'), (0, 'Fuse Box over 60 AMP and all Romex wiring (Average)'), (1, '60 AMP Fuse Box and mostly Romex wiring (Fair)'), (4, 'Standard Circuit Breakers & Romex'), (2, '60 AMP Fuse Box and mostly knob & tube wiring (poor)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Foundation',
            field=models.PositiveIntegerField(choices=[(0, 'Brick & Tile'), (3, 'Slab'), (5, 'Wood'), (2, 'Poured Contrete'), (1, 'Cinder Block'), (4, 'Stone')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='GarageType',
            field=models.PositiveIntegerField(choices=[(3, 'Built-In (Garage part of house - typically has room above garage)'), (2, 'Basement Garage'), (1, 'Attached to home'), (4, 'Car Port'), (5, 'Detached from home'), (0, 'More than one type of garage')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HeatingQC',
            field=models.PositiveIntegerField(choices=[(1, 'Fair'), (2, 'Good'), (4, 'Average/Typical'), (3, 'Poor'), (0, 'Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HouseStyle',
            field=models.PositiveIntegerField(choices=[(6, 'Split Foyer'), (4, 'Two and one-half story: 2nd level unfinished'), (0, 'One and one-half story: 2nd level finished'), (2, 'One story'), (3, 'Two and one-half story: 2nd level finished'), (1, 'One and one-half story: 2nd level unfinished'), (7, 'Split Level'), (5, 'Two story')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='LotShape',
            field=models.PositiveIntegerField(choices=[(2, 'Irregular'), (3, 'Regular'), (1, 'Moderately Irregular'), (0, 'Slightly irregular')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Neighborhood',
            field=models.PositiveIntegerField(choices=[(15, 'Northridge'), (16, 'Northridge Heights'), (1, 'Bluestem'), (20, 'Sawyer West'), (0, 'Bloomington Heights'), (12, 'Northwest Ames'), (5, 'College Creek'), (17, 'Old Town'), (4, 'Clear Creek'), (2, 'Briardale'), (6, 'Crawford'), (8, 'Gilbert'), (14, 'North Ames'), (24, 'Veenker'), (7, 'Edwards'), (3, 'Brookside'), (11, 'Mitchell'), (19, 'Sawyer'), (21, 'Somerset'), (9, 'Iowa DOT and Rail Road'), (10, 'Meadow Village'), (18, 'South & West of Iowa State University'), (13, 'Northpark Villa'), (22, 'Stone Brook'), (23, 'Timberland')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PavedDrive',
            field=models.PositiveIntegerField(choices=[(2, 'Paved '), (0, 'Dirt/Gravel'), (1, 'Partial Pavement')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofMatl',
            field=models.PositiveIntegerField(choices=[(4, 'Roll'), (6, 'Wood Shakes'), (0, 'Clay or Tile'), (1, 'Standard (Composite) Shingle'), (5, 'Gravel & Tar'), (3, 'Metal'), (2, 'Membrane'), (7, 'Wood Shingles')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofStyle',
            field=models.PositiveIntegerField(choices=[(3, 'Hip'), (0, 'Flat'), (2, 'Gabrel (Barn)'), (1, 'Gable'), (4, 'Mansard'), (5, 'Shed')], null=True),
        ),
    ]
