# Generated by Django 4.0.4 on 2022-07-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_alter_data_bldgtype_alter_data_bsmtqual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BldgType',
            field=models.PositiveIntegerField(choices=[(4, 'Townhouse End Unit'), (0, 'Single-family Detached'), (3, 'Townhouse Inside Unit'), (1, 'Two-family Conversion; originally built as one-family dwelling'), (2, 'Duplex')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='BsmtQual',
            field=models.PositiveIntegerField(choices=[(1, 'Fair (70-79 inches)'), (3, 'Typical (80-89 inches)'), (0, 'Excellent (100+ inches)'), (2, 'Good (90-99 inches)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Electrical',
            field=models.PositiveIntegerField(choices=[(2, '60 AMP Fuse Box and mostly knob & tube wiring (poor)'), (1, '60 AMP Fuse Box and mostly Romex wiring (Fair)'), (3, 'Mixed'), (0, 'Fuse Box over 60 AMP and all Romex wiring (Average)'), (4, 'Standard Circuit Breakers & Romex')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Foundation',
            field=models.PositiveIntegerField(choices=[(1, 'Cinder Block'), (0, 'Brick & Tile'), (5, 'Wood'), (3, 'Slab'), (2, 'Poured Contrete'), (4, 'Stone')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='GarageType',
            field=models.PositiveIntegerField(choices=[(5, 'Detached from home'), (0, 'More than one type of garage'), (1, 'Attached to home'), (3, 'Built-In (Garage part of house - typically has room above garage)'), (2, 'Basement Garage'), (4, 'Car Port')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HeatingQC',
            field=models.PositiveIntegerField(choices=[(2, 'Good'), (4, 'Average/Typical'), (3, 'Poor'), (1, 'Fair'), (0, 'Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HouseStyle',
            field=models.PositiveIntegerField(choices=[(5, 'Two story'), (0, 'One and one-half story: 2nd level finished'), (6, 'Split Foyer'), (4, 'Two and one-half story: 2nd level unfinished'), (3, 'Two and one-half story: 2nd level finished'), (7, 'Split Level'), (1, 'One and one-half story: 2nd level unfinished'), (2, 'One story')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='LotShape',
            field=models.PositiveIntegerField(choices=[(3, 'Regular'), (1, 'Moderately Irregular'), (2, 'Irregular'), (0, 'Slightly irregular')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Neighborhood',
            field=models.PositiveIntegerField(choices=[(2, 'Briardale'), (5, 'College Creek'), (23, 'Timberland'), (16, 'Northridge Heights'), (6, 'Crawford'), (21, 'Somerset'), (8, 'Gilbert'), (0, 'Bloomington Heights'), (3, 'Brookside'), (24, 'Veenker'), (10, 'Meadow Village'), (4, 'Clear Creek'), (7, 'Edwards'), (20, 'Sawyer West'), (19, 'Sawyer'), (17, 'Old Town'), (22, 'Stone Brook'), (15, 'Northridge'), (18, 'South & West of Iowa State University'), (12, 'Northwest Ames'), (1, 'Bluestem'), (11, 'Mitchell'), (9, 'Iowa DOT and Rail Road'), (14, 'North Ames'), (13, 'Northpark Villa')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PavedDrive',
            field=models.PositiveIntegerField(choices=[(1, 'Partial Pavement'), (0, 'Dirt/Gravel'), (2, 'Paved ')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofMatl',
            field=models.PositiveIntegerField(choices=[(4, 'Roll'), (6, 'Wood Shakes'), (2, 'Membrane'), (1, 'Standard (Composite) Shingle'), (5, 'Gravel & Tar'), (7, 'Wood Shingles'), (0, 'Clay or Tile'), (3, 'Metal')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofStyle',
            field=models.PositiveIntegerField(choices=[(5, 'Shed'), (1, 'Gable'), (3, 'Hip'), (2, 'Gabrel (Barn)'), (0, 'Flat'), (4, 'Mansard')], null=True),
        ),
    ]
