# Generated by Django 4.0.4 on 2022-07-11 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0008_alter_data_bldgtype_alter_data_bsmtqual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='BldgType',
            field=models.PositiveIntegerField(choices=[(0, 'Single-family Detached'), (4, 'Townhouse End Unit'), (3, 'Townhouse Inside Unit'), (2, 'Duplex'), (1, 'Two-family Conversion; originally built as one-family dwelling')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='CentralAir',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Electrical',
            field=models.PositiveIntegerField(choices=[(3, 'Mixed'), (0, 'Fuse Box over 60 AMP and all Romex wiring (Average)'), (4, 'Standard Circuit Breakers & Romex'), (2, '60 AMP Fuse Box and mostly knob & tube wiring (poor)'), (1, '60 AMP Fuse Box and mostly Romex wiring (Fair)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Foundation',
            field=models.PositiveIntegerField(choices=[(1, 'Cinder Block'), (5, 'Wood'), (2, 'Poured Contrete'), (0, 'Brick & Tile'), (4, 'Stone'), (3, 'Slab')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='GarageType',
            field=models.PositiveIntegerField(choices=[(4, 'Car Port'), (5, 'Detached from home'), (2, 'Basement Garage'), (1, 'Attached to home'), (3, 'Built-In (Garage part of house - typically has room above garage)'), (0, 'More than one type of garage')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HeatingQC',
            field=models.PositiveIntegerField(choices=[(1, 'Fair'), (4, 'Average/Typical'), (2, 'Good'), (0, 'Excellent'), (3, 'Poor')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HouseStyle',
            field=models.PositiveIntegerField(choices=[(2, 'One story'), (6, 'Split Foyer'), (1, 'One and one-half story: 2nd level unfinished'), (7, 'Split Level'), (5, 'Two story'), (4, 'Two and one-half story: 2nd level unfinished'), (0, 'One and one-half story: 2nd level finished'), (3, 'Two and one-half story: 2nd level finished')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='LotShape',
            field=models.PositiveIntegerField(choices=[(2, 'Irregular'), (1, 'Moderately Irregular'), (0, 'Slightly irregular'), (3, 'Regular')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Neighborhood',
            field=models.PositiveIntegerField(choices=[(13, 'Northpark Villa'), (10, 'Meadow Village'), (3, 'Brookside'), (22, 'Stone Brook'), (24, 'Veenker'), (16, 'Northridge Heights'), (18, 'South & West of Iowa State University'), (9, 'Iowa DOT and Rail Road'), (21, 'Somerset'), (11, 'Mitchell'), (20, 'Sawyer West'), (2, 'Briardale'), (6, 'Crawford'), (7, 'Edwards'), (14, 'North Ames'), (19, 'Sawyer'), (4, 'Clear Creek'), (23, 'Timberland'), (15, 'Northridge'), (8, 'Gilbert'), (12, 'Northwest Ames'), (0, 'Bloomington Heights'), (1, 'Bluestem'), (5, 'College Creek'), (17, 'Old Town')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PavedDrive',
            field=models.PositiveIntegerField(choices=[(0, 'Dirt/Gravel'), (1, 'Partial Pavement'), (2, 'Paved ')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofMatl',
            field=models.PositiveIntegerField(choices=[(4, 'Roll'), (1, 'Standard (Composite) Shingle'), (3, 'Metal'), (2, 'Membrane'), (0, 'Clay or Tile'), (6, 'Wood Shakes'), (5, 'Gravel & Tar'), (7, 'Wood Shingles')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofStyle',
            field=models.PositiveIntegerField(choices=[(4, 'Mansard'), (2, 'Gabrel (Barn)'), (3, 'Hip'), (0, 'Flat'), (1, 'Gable'), (5, 'Shed')], null=True),
        ),
        migrations.CreateModel(
            name='PredictionAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
