# Generated by Django 4.0.4 on 2022-07-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0011_rename_prediction_author_id_predictionauthor_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BldgType',
            field=models.PositiveIntegerField(choices=[(3, 'Townhouse Inside Unit'), (0, 'Single-family Detached'), (1, 'Two-family Conversion; originally built as one-family dwelling'), (4, 'Townhouse End Unit'), (2, 'Duplex')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='BsmtQual',
            field=models.PositiveIntegerField(choices=[(0, 'Excellent (100+ inches)'), (1, 'Fair (70-79 inches)'), (2, 'Good (90-99 inches)'), (3, 'Typical (80-89 inches)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Electrical',
            field=models.PositiveIntegerField(choices=[(3, 'Mixed'), (0, 'Fuse Box over 60 AMP and all Romex wiring (Average)'), (4, 'Standard Circuit Breakers & Romex'), (1, '60 AMP Fuse Box and mostly Romex wiring (Fair)'), (2, '60 AMP Fuse Box and mostly knob & tube wiring (poor)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Foundation',
            field=models.PositiveIntegerField(choices=[(4, 'Stone'), (0, 'Brick & Tile'), (2, 'Poured Contrete'), (5, 'Wood'), (1, 'Cinder Block'), (3, 'Slab')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='GarageType',
            field=models.PositiveIntegerField(choices=[(1, 'Attached to home'), (2, 'Basement Garage'), (4, 'Car Port'), (5, 'Detached from home'), (0, 'More than one type of garage'), (3, 'Built-In (Garage part of house - typically has room above garage)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HeatingQC',
            field=models.PositiveIntegerField(choices=[(3, 'Poor'), (1, 'Fair'), (4, 'Average/Typical'), (2, 'Good'), (0, 'Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HouseStyle',
            field=models.PositiveIntegerField(choices=[(2, 'One story'), (3, 'Two and one-half story: 2nd level finished'), (4, 'Two and one-half story: 2nd level unfinished'), (0, 'One and one-half story: 2nd level finished'), (6, 'Split Foyer'), (7, 'Split Level'), (5, 'Two story'), (1, 'One and one-half story: 2nd level unfinished')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='LotShape',
            field=models.PositiveIntegerField(choices=[(0, 'Slightly irregular'), (1, 'Moderately Irregular'), (3, 'Regular'), (2, 'Irregular')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Neighborhood',
            field=models.PositiveIntegerField(choices=[(2, 'Briardale'), (5, 'College Creek'), (13, 'Northpark Villa'), (17, 'Old Town'), (12, 'Northwest Ames'), (8, 'Gilbert'), (10, 'Meadow Village'), (18, 'South & West of Iowa State University'), (7, 'Edwards'), (0, 'Bloomington Heights'), (22, 'Stone Brook'), (6, 'Crawford'), (9, 'Iowa DOT and Rail Road'), (3, 'Brookside'), (15, 'Northridge'), (19, 'Sawyer'), (1, 'Bluestem'), (4, 'Clear Creek'), (21, 'Somerset'), (14, 'North Ames'), (23, 'Timberland'), (20, 'Sawyer West'), (16, 'Northridge Heights'), (24, 'Veenker'), (11, 'Mitchell')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PavedDrive',
            field=models.PositiveIntegerField(choices=[(2, 'Paved '), (0, 'Dirt/Gravel'), (1, 'Partial Pavement')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofMatl',
            field=models.PositiveIntegerField(choices=[(6, 'Wood Shakes'), (0, 'Clay or Tile'), (4, 'Roll'), (2, 'Membrane'), (5, 'Gravel & Tar'), (3, 'Metal'), (7, 'Wood Shingles'), (1, 'Standard (Composite) Shingle')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofStyle',
            field=models.PositiveIntegerField(choices=[(1, 'Gable'), (2, 'Gabrel (Barn)'), (5, 'Shed'), (0, 'Flat'), (3, 'Hip'), (4, 'Mansard')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Street',
            field=models.PositiveIntegerField(choices=[(1, 'Paved'), (0, 'Gravel')], null=True),
        ),
        migrations.DeleteModel(
            name='PredictionAuthor',
        ),
    ]
