# Generated by Django 4.0.4 on 2022-07-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0014_rename_userprofile_account_alter_data_bldgtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BldgType',
            field=models.PositiveIntegerField(choices=[(3, 'Townhouse Inside Unit'), (0, 'Single-family Detached'), (4, 'Townhouse End Unit'), (1, 'Two-family Conversion; originally built as one-family dwelling'), (2, 'Duplex')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='BsmtQual',
            field=models.PositiveIntegerField(choices=[(1, 'Fair (70-79 inches)'), (3, 'Typical (80-89 inches)'), (2, 'Good (90-99 inches)'), (0, 'Excellent (100+ inches)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='CentralAir',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Electrical',
            field=models.PositiveIntegerField(choices=[(3, 'Mixed'), (0, 'Fuse Box over 60 AMP and all Romex wiring (Average)'), (1, '60 AMP Fuse Box and mostly Romex wiring (Fair)'), (2, '60 AMP Fuse Box and mostly knob & tube wiring (poor)'), (4, 'Standard Circuit Breakers & Romex')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Foundation',
            field=models.PositiveIntegerField(choices=[(0, 'Brick & Tile'), (1, 'Cinder Block'), (3, 'Slab'), (2, 'Poured Contrete'), (4, 'Stone'), (5, 'Wood')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='GarageType',
            field=models.PositiveIntegerField(choices=[(1, 'Attached to home'), (2, 'Basement Garage'), (3, 'Built-In (Garage part of house - typically has room above garage)'), (5, 'Detached from home'), (0, 'More than one type of garage'), (4, 'Car Port')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HeatingQC',
            field=models.PositiveIntegerField(choices=[(0, 'Excellent'), (2, 'Good'), (4, 'Average/Typical'), (3, 'Poor'), (1, 'Fair')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HouseStyle',
            field=models.PositiveIntegerField(choices=[(7, 'Split Level'), (0, 'One and one-half story: 2nd level finished'), (2, 'One story'), (4, 'Two and one-half story: 2nd level unfinished'), (3, 'Two and one-half story: 2nd level finished'), (1, 'One and one-half story: 2nd level unfinished'), (6, 'Split Foyer'), (5, 'Two story')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='LotShape',
            field=models.PositiveIntegerField(choices=[(0, 'Slightly irregular'), (2, 'Irregular'), (3, 'Regular'), (1, 'Moderately Irregular')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Neighborhood',
            field=models.PositiveIntegerField(choices=[(6, 'Crawford'), (19, 'Sawyer'), (20, 'Sawyer West'), (8, 'Gilbert'), (18, 'South & West of Iowa State University'), (17, 'Old Town'), (24, 'Veenker'), (5, 'College Creek'), (0, 'Bloomington Heights'), (1, 'Bluestem'), (15, 'Northridge'), (3, 'Brookside'), (13, 'Northpark Villa'), (12, 'Northwest Ames'), (7, 'Edwards'), (22, 'Stone Brook'), (2, 'Briardale'), (10, 'Meadow Village'), (11, 'Mitchell'), (4, 'Clear Creek'), (21, 'Somerset'), (16, 'Northridge Heights'), (14, 'North Ames'), (23, 'Timberland'), (9, 'Iowa DOT and Rail Road')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PavedDrive',
            field=models.PositiveIntegerField(choices=[(1, 'Partial Pavement'), (0, 'Dirt/Gravel'), (2, 'Paved ')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofMatl',
            field=models.PositiveIntegerField(choices=[(6, 'Wood Shakes'), (3, 'Metal'), (4, 'Roll'), (7, 'Wood Shingles'), (2, 'Membrane'), (1, 'Standard (Composite) Shingle'), (5, 'Gravel & Tar'), (0, 'Clay or Tile')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofStyle',
            field=models.PositiveIntegerField(choices=[(5, 'Shed'), (4, 'Mansard'), (0, 'Flat'), (3, 'Hip'), (1, 'Gable'), (2, 'Gabrel (Barn)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Street',
            field=models.PositiveIntegerField(choices=[(0, 'Gravel'), (1, 'Paved')], null=True),
        ),
    ]
