# Generated by Django 4.0.4 on 2022-07-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0015_alter_data_bldgtype_alter_data_bsmtqual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BldgType',
            field=models.PositiveIntegerField(choices=[(3, 'Townhouse Inside Unit'), (1, 'Two-family Conversion; originally built as one-family dwelling'), (0, 'Single-family Detached'), (2, 'Duplex'), (4, 'Townhouse End Unit')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='BsmtQual',
            field=models.PositiveIntegerField(choices=[(1, 'Fair (70-79 inches)'), (0, 'Excellent (100+ inches)'), (2, 'Good (90-99 inches)'), (3, 'Typical (80-89 inches)')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Electrical',
            field=models.PositiveIntegerField(choices=[(1, '60 AMP Fuse Box and mostly Romex wiring (Fair)'), (0, 'Fuse Box over 60 AMP and all Romex wiring (Average)'), (3, 'Mixed'), (2, '60 AMP Fuse Box and mostly knob & tube wiring (poor)'), (4, 'Standard Circuit Breakers & Romex')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Foundation',
            field=models.PositiveIntegerField(choices=[(2, 'Poured Contrete'), (1, 'Cinder Block'), (5, 'Wood'), (3, 'Slab'), (0, 'Brick & Tile'), (4, 'Stone')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='GarageType',
            field=models.PositiveIntegerField(choices=[(2, 'Basement Garage'), (1, 'Attached to home'), (0, 'More than one type of garage'), (3, 'Built-In (Garage part of house - typically has room above garage)'), (5, 'Detached from home'), (4, 'Car Port')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HeatingQC',
            field=models.PositiveIntegerField(choices=[(0, 'Excellent'), (1, 'Fair'), (4, 'Average/Typical'), (3, 'Poor'), (2, 'Good')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='HouseStyle',
            field=models.PositiveIntegerField(choices=[(0, 'One and one-half story: 2nd level finished'), (5, 'Two story'), (4, 'Two and one-half story: 2nd level unfinished'), (2, 'One story'), (7, 'Split Level'), (1, 'One and one-half story: 2nd level unfinished'), (3, 'Two and one-half story: 2nd level finished'), (6, 'Split Foyer')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='LotShape',
            field=models.PositiveIntegerField(choices=[(3, 'Regular'), (1, 'Moderately Irregular'), (0, 'Slightly irregular'), (2, 'Irregular')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Neighborhood',
            field=models.PositiveIntegerField(choices=[(6, 'Crawford'), (18, 'South & West of Iowa State University'), (9, 'Iowa DOT and Rail Road'), (14, 'North Ames'), (24, 'Veenker'), (15, 'Northridge'), (20, 'Sawyer West'), (13, 'Northpark Villa'), (3, 'Brookside'), (1, 'Bluestem'), (10, 'Meadow Village'), (7, 'Edwards'), (23, 'Timberland'), (19, 'Sawyer'), (22, 'Stone Brook'), (0, 'Bloomington Heights'), (2, 'Briardale'), (5, 'College Creek'), (16, 'Northridge Heights'), (8, 'Gilbert'), (11, 'Mitchell'), (21, 'Somerset'), (17, 'Old Town'), (4, 'Clear Creek'), (12, 'Northwest Ames')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='PavedDrive',
            field=models.PositiveIntegerField(choices=[(1, 'Partial Pavement'), (2, 'Paved '), (0, 'Dirt/Gravel')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofMatl',
            field=models.PositiveIntegerField(choices=[(4, 'Roll'), (0, 'Clay or Tile'), (2, 'Membrane'), (7, 'Wood Shingles'), (6, 'Wood Shakes'), (5, 'Gravel & Tar'), (3, 'Metal'), (1, 'Standard (Composite) Shingle')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='RoofStyle',
            field=models.PositiveIntegerField(choices=[(3, 'Hip'), (0, 'Flat'), (2, 'Gabrel (Barn)'), (4, 'Mansard'), (5, 'Shed'), (1, 'Gable')], null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Street',
            field=models.PositiveIntegerField(choices=[(1, 'Paved'), (0, 'Gravel')], null=True),
        ),
    ]
